# Generated by Django 2.1.7 on 2019-03-15 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('symptoms', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birthday', models.DateField(blank=True, null=True, verbose_name='date_of_birthday')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='gender')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('city', models.CharField(blank=True, max_length=45, null=True, verbose_name='city')),
                ('mail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='mail')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='phone_number')),
                ('name_of_organisation', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'DoctorType',
                'verbose_name_plural': 'DoctorType',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('diseases', models.ManyToManyField(to='database.Disease')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=2)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_whom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_whom', to=settings.AUTH_USER_MODEL)),
                ('to_whom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_whom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birthday', models.DateField(blank=True, null=True, verbose_name='date_of_birthday')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='gender')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('city', models.CharField(blank=True, max_length=45, null=True, verbose_name='city')),
                ('mail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='mail')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='phone_number')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('diseases', models.ManyToManyField(to='database.Disease')),
                ('doctors', models.ManyToManyField(to='database.Doctor')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.AddField(
            model_name='measurementfrequency',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DoctorType'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disease',
            name='doctorType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DoctorType'),
        ),
    ]
