# Generated by Django 2.1.7 on 2019-03-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctortype',
            options={'verbose_name': 'DoctorType', 'verbose_name_plural': 'DoctorType'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
    ]
