# Generated by Django 2.1.7 on 2019-03-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diseases',
            field=models.ManyToManyField(blank=True, null=True, to='database.Disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, to='database.Doctor'),
        ),
    ]
