# Generated by Django 2.1.7 on 2019-03-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190317_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_whom',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_whom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
