# Generated by Django 2.1.7 on 2019-03-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190323_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctortype',
            options={'verbose_name': 'DoctorType', 'verbose_name_plural': 'DoctorTypes'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AddField(
            model_name='measurement',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Patient'),
        ),
    ]
