# Generated by Django 2.1.7 on 2019-04-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190330_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='date',
        ),
    ]
