# Generated by Django 2.1.7 on 2019-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_measurement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='testimony',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
