# Generated by Django 2.1.7 on 2019-05-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190423_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='type',
            new_name='indicator',
        ),
    ]
