# Generated by Django 2.1.7 on 2019-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20190501_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='second_name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='second_name'),
        ),
    ]
