# Generated by Django 2.1.7 on 2019-05-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190503_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementfrequency',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='measurementfrequency',
            name='patient',
        ),
        migrations.DeleteModel(
            name='MeasurementFrequency',
        ),
    ]
