# Generated by Django 2.1.7 on 2019-05-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20190506_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='doctor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
